DFK_EVENT_WORDS = {
    'Quest',
    'AuctionHouse',
    'LandAuction',
    'Uniswap',
    'Gardener',
    'Farms',
    'Lending',
    'Airdrop',
    'Payment Service',
    'Banker',
    'Vendor',
    'Summoning',
    'PetIncubator',
    'Meditation',
    'Alchemist',
    'Stone Carver',
    'HeroSale',
    'anySwap',
    'Bridge',
    'Potion Use',
    'Perilous Journey',
    'PetTradeIn',
    'DFKDuel'
}